apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "REPLACE_WITH_YOUR_REPO_URL"
    targetRevision: HEAD
    path: charts/backend
    helm:
      valueFiles:
        - envs/dev/backend-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
